name: iClan
version: "1.0.0"
main: com.naufalverse.iclan.IClanPlugin
api-version: "1.21"
author: NaufalVerse & incognit56
description: A clan management plugin for Minecraft servers

commands:
  clan:
    description: Main clan management command
    usage: "/clan create <name> - Create a new clan"
    aliases: [clans, c]
    permission: clans.use
    permission-message: "You don't have permission to use clan commands!"

permissions:
  clans.use:
    description: Basic permission to use clan commands
    default: true
  clans.create:
    description: Permission to create a clan
    default: true
  clans.admin:
    description: Admin permissions for clan management
    default: op
    children:
      clans.use: true
      clans.create: true