name: iClan
version: ${project.version}
main: com.naufalverse.iclan.IClanPlugin
api-version: 1.21
author: NaufalVerse
description: A simple clan management plugin for PaperMC servers
website: https://naufalverse.com

commands:
  clan:
    description: Main clan command
    usage: /clan <subcommand>
    aliases: [c, clans]
    permission-message: "You don't have permission to use this command!"

permissions:
  iclan.user:
    description: Allows basic clan usage
    default: true
    children:
      iclan.create: true
      iclan.join: true
      iclan.leave: true
      iclan.info: true
      iclan.list: true
  
  iclan.create:
    description: Allows creating clans
    default: true
  
  iclan.join:
    description: Allows joining clans
    default: true
  
  iclan.leave:
    description: Allows leaving clans
    default: true
  
  iclan.info:
    description: Allows viewing clan information
    default: true
  
  iclan.list:
    description: Allows listing all clans
    default: true
  
  iclan.owner:
    description: Allows clan owner commands
    default: false
    children:
      iclan.accept: true
      iclan.kick: true
      iclan.disband: true
  
  iclan.accept:
    description: Allows accepting clan members
    default: false
  
  iclan.kick:
    description: Allows kicking clan members
    default: false
  
  iclan.disband:
    description: Allows disbanding clans
    default: false
  
  iclan.admin:
    description: Allows admin commands
    default: op
    children:
      iclan.user: true
      iclan.owner: true
      iclan.reload: true
      iclan.backup: true
  
  iclan.reload:
    description: Allows reloading the plugin
    default: op
  
  iclan.backup:
    description: Allows backing up clan data
    default: op